Repository stolostron/compute-operator, pull requests merged in 2022-07, with the labels that each got.

#15 initial steps to get E2E tests from prow going
  Dockerfile.cypress
  Makefile
  test/e2e/download-clis.sh
  test/e2e/install-compute-operator.sh
  test/e2e/run-prow-e2e.sh
  test/e2e/setup-go.sh
Labels: approved, dco-signoff: yes

#17 a few more tweaks
  test/e2e/install-compute-operator.sh
  test/e2e/start-cypress-tests.sh
Labels: lgtm, dco-signoff: yes

#18 Copy E2E test changes from test to main
  Dockerfile.cypress
  Makefile
  test/e2e/download-clis.sh
  test/e2e/install-compute-operator.sh
  test/e2e/run-prow-e2e.sh
  test/e2e/setup-go.sh
  test/e2e/start-cypress-tests.sh
Labels: approved, lgtm, dco-signoff: no

#20 Convert configmap importcmd to secret
  controllers/cluster-registration/cluster_registration_controller.go
  controllers/cluster-registration/suite_test.go
  hack/compute/role.yaml
  resources/cluster-registration/import_secret.yaml
Labels: approved, lgtm, dco-signoff: yes

#23 Debug
  CONTRIBUTING.md
  controllers/cluster-registration/controller.go
  controllers/cluster-registration/suite_test.go
  controllers/installer/controller.go
  controllers/installer/suite_test.go
  main.go
Labels: approved, lgtm, dco-signoff: yes

#26 remove managed cluster claim
  test/e2e/run-prow-e2e.sh
Labels: approved, lgtm, dco-signoff: yes

#27 externalize kcp setup/teardown for ginkgo suite
  Makefile
  controllers/cluster-registration/suite_test.go
  go.mod
  go.sum
  test/compute_suite.go
Labels: approved, lgtm, dco-signoff: yes

#29 Add webhook suite_test
  .gitignore
  CONTRIBUTING.md
  Dockerfile
  Makefile
  build/generate_kubeconfig_from_sa.sh
  cmd/webhook/main.go
  controllers/cluster-registration/suite_test.go
  controllers/installer/suite_test.go
  go.mod
  go.sum
  main.go
  test/compute_suite.go
  test/resources/compute/clusterRegistrar.yaml
  webhook/suite_test.go
  webhook/webhook.go
Labels: approved, lgtm, dco-signoff: yes

#31 deploy kcp syncer via manifestwork
  controllers/cluster-registration/cluster_registration_controller.go
  controllers/cluster-registration/controller.go
  controllers/cluster-registration/suite_test.go
  hack/compute/apibinding.yaml
  hack/compute/apiexport.yaml
  hack/compute/namespace.yaml
  hack/compute/role.yaml
  hack/compute/service_account.yaml
  pkg/helpers/workspace.go
  resources/cluster-registration/kcp_syncer_clusterrole.yaml
  resources/cluster-registration/kcp_syncer_clusterrolebinding.yaml
  resources/cluster-registration/kcp_syncer_manifestwork.yaml
  resources/cluster-registration/kubeconfig_secret.yaml
  resources/cluster-registration/managed_cluster_addon.yaml
  resources/cluster-registration/managed_service_account.yaml
  resources/cluster-registration/service_account_roles.yaml
  resources/compute-templates/virtual-workspace/apiexport.yaml
  resources/compute-templates/workspace/apibinding.yaml
  test/compute_suite.go
  test/resources/compute/registeredCluster.yaml
  webhook/suite_test.go
Labels: approved, lgtm, dco-signoff: yes

#32 fix sonar vulnerabilities
  test/compute_suite.go
Labels: approved, lgtm, dco-signoff: yes

#30 update git action to go 1.18 and update readme with unit test info
  .github/workflows/publish.yml
  .github/workflows/release.yml
  Makefile
  README.md
Labels: approved, lgtm, dco-signoff: yes

#33 support running on kcp
  Makefile
  README.md
  config/apiresourceschema/singapore.open-cluster-management.io_clusterregistrars.yaml
  config/apiresourceschema/singapore.open-cluster-management.io_hubconfigs.yaml
  config/installer/config.properties
  config/installer/installer.yaml
  config/installer/kustomization.yaml
  config/rbac/role.yaml
  controllers/cluster-registration/controller.go
  controllers/cluster-registration/suite_test.go
  controllers/installer/controller.go
  controllers/installer/installer_controller.go
  controllers/installer/suite_test.go
  deploy/compute-operator/clusterrole.yaml
  hack/compute/role.yaml
  hack/compute/role_binding.yaml
  resources/compute-templates/virtual-workspace/apiexport.yaml
  resources/compute-templates/virtual-workspace/role.yaml
  resources/compute-templates/virtual-workspace/role_binding.yaml
Labels: approved, lgtm, dco-signoff: yes
