Repository stolostron/compute-operator, pull requests merged in 2022-08, with the labels that each got.

#34 add v prefix to tag name
  .github/workflows/release.yml
Labels: approved, lgtm, dco-signoff: yes

#37 vcluster does not support oc new-project command
  test/e2e/install-compute-operator.sh
Labels: approved, lgtm, dco-signoff: yes

#35 Remove clusteradm dependency
  Makefile
  config/resources.go
  controllers/cluster-registration/cluster_registration_controller.go
  controllers/cluster-registration/controller.go
  controllers/installer/installer_controller.go
  controllers/installer/suite_test.go
  deploy/resources.go
  go.mod
  go.sum
  hack/compute/apibinding.yaml
  hack/compute/namespace.yaml
  hack/compute/service_account.yaml
  hack/resources.go
  pkg/helpers/hub.go
  resources/compute-templates/hack-values.yaml
  resources/compute-templates/workspace/apibinding.yaml
  resources/resources.go
  test/compute_suite.go
  test/resources.go
Labels: approved, lgtm, dco-signoff: yes

#24 CMCS-161: Add vcluster to e2e cli
  test/e2e/download-clis.sh
  test/e2e/run-prow-e2e.sh
Labels: approved, lgtm, dco-signoff: yes

#28 create synctarget in the location namespace
  Makefile
  README.md
  controllers/cluster-registration/cluster_registration_controller.go
  controllers/cluster-registration/suite_test.go
  go.mod
  go.sum
  hack/compute/apibinding.yaml
  hack/compute/apiexport.yaml
  resources/compute-templates/virtual-workspace/apiexport.yaml
  resources/compute-templates/workspace/apibinding.yaml
  test/compute_suite.go
  webhook/suite_test.go
Labels: approved, lgtm, dco-signoff: yes

#39 update synctarget with registeredcluster labels
  controllers/cluster-registration/cluster_registration_controller.go
  controllers/cluster-registration/suite_test.go
Labels: approved, dco-signoff: yes

#38 support multiple locations in registeredcluster
  Makefile
  README.md
  api/singapore/v1alpha1/registeredcluster_types.go
  api/singapore/v1alpha1/zz_generated.deepcopy.go
  config/apiresourceschema/singapore.open-cluster-management.io_registeredclusters.yaml
  config/crd/singapore.open-cluster-management.io_registeredclusters.yaml
  controllers/cluster-registration/cluster_registration_controller.go
  controllers/cluster-registration/suite_test.go
  go.mod
  go.sum
  pkg/helpers/workspace.go
  test/compute_suite.go
  test/resources/compute/registeredCluster.yaml
Labels: approved, lgtm, dco-signoff: yes

#40 fix SKIP_WEBHOOK configmap env var
  config/installer/installer.yaml
  controllers/installer/installer_controller.go
Labels: approved, lgtm, dco-signoff: yes

#41 create clusterrole and clusterrolebinding for syncer service account
  Makefile
  controllers/cluster-registration/cluster_registration_controller.go
  controllers/cluster-registration/suite_test.go
  hack/compute/apibinding.yaml
  hack/compute/apiexport.yaml
  pkg/helpers/workspace.go
  resources/compute-templates/virtual-workspace/apiexport.yaml
  resources/compute-templates/workspace/apibinding.yaml
Labels: approved, lgtm, dco-signoff: yes

#43 add sync-target-uid arg to syncer deployment
  controllers/cluster-registration/cluster_registration_controller.go
  resources/cluster-registration/kcp_syncer_manifestwork.yaml
Labels: approved, lgtm, dco-signoff: yes

#42 add managedcluster to managedclusterset
  controllers/cluster-registration/cluster_registration_controller.go
  controllers/cluster-registration/suite_test.go
  pkg/helpers/workspace.go
  pkg/helpers/workspace_test.go
  test/compute_suite.go
  test/config/crd/external/0000_00_clusters.open-cluster-management.io_managedclustersets.crd.yaml
Labels: approved, lgtm, dco-signoff: yes

#44 update directions for running on kcp
  Makefile
  README.md
  config/apiresourceschema/singapore.open-cluster-management.io_clusterregistrars.yaml
  config/apiresourceschema/singapore.open-cluster-management.io_hubconfigs.yaml
Labels: approved, lgtm, dco-signoff: yes

#48 Update kcp_syncer_manifestwork.yaml
  resources/cluster-registration/kcp_syncer_manifestwork.yaml
Labels: approved, lgtm, dco-signoff: no

#51 fix version number used by quay image - ACM main tooling updated to 2…
  test/e2e/install-compute-operator.sh
Labels: approved, dco-signoff: yes

#46 process deletion of registeredcluster
  Makefile
  controllers/cluster-registration/cluster_registration_controller.go
  controllers/cluster-registration/suite_test.go
Labels: approved, dco-signoff: yes

#50 requeue when service account secret is not yet ready
  controllers/cluster-registration/cluster_registration_controller.go
Labels: approved, lgtm, dco-signoff: yes
