Repository stolostron/compute-operator, pull requests merged in 2022-06, with the labels that each got.

#1 Migrate kcp
  cmd/manager/main.go
  controllers/cluster-registration/cluster_registration_controller.go
  controllers/cluster-registration/suite_test.go
  controllers/installer/installer_controller.go
  controllers/installer/suite_test.go
  controllers/workspace/workspace_controller.go
  go.mod
  go.sum
  pkg/helpers/hub.go
Labels: approved

#2 Add Metrics and make it working on kcp
  Makefile
  README.md
  api/singapore/v1alpha1/clusterregistrar_types.go
  api/singapore/v1alpha1/hubconfig_type.go
  api/singapore/v1alpha1/zz_generated.deepcopy.go
  build/generate_kubeconfig_from_sa.sh
  cmd/installer/main.go
  cmd/manager/main.go
  config/apiresourceschema/singapore.open-cluster-management.io_registeredclusters.yaml
  config/crd/singapore.open-cluster-management.io_clusterregistrars.yaml
  config/crd/singapore.open-cluster-management.io_hubconfigs.yaml
  config/installer/kustomization.yaml
  config/manager/manager.yaml
  controllers/cluster-registration/cluster_registration_controller.go
  controllers/cluster-registration/suite_test.go
  controllers/installer/installer_controller.go
  deploy/compute-operator/manager.yaml
  go.mod
  go.sum
  hack/compute/apibinding.yaml
  hack/compute/apiexport.yaml
  hack/compute/role.yaml
  hack/compute/role_binding.yaml
  main.go
  pkg/helpers/cache.go
  pkg/helpers/gvr.go
  pkg/helpers/hub.go
Labels: approved, lgtm

#3 fix copyright errors on make check
  .copyrightignore
  build/generate_kubeconfig_from_sa.sh
Labels: approved

#4 test prow build
  .triggerbuild
Labels: approved, lgtm

#5 Add make target and README for developing manager locally
  .vscode/launch.json
  Makefile
  README.md
  config/apiresourceschema/singapore.open-cluster-management.io_registeredclusters.yaml
  hack/clusterregistrar.yaml
  hack/compute/apiexport.yaml
  hack/compute/role.yaml
  hack/hubconfig.yaml
Labels: approved, lgtm

#7 minor README and makefile tweaks
  Makefile
  README.md
Labels: approved, lgtm, dco-signoff: yes

#8 add kcp location to registeredcluster CR
  .copyrightignore
  Makefile
  api/singapore/v1alpha1/registeredcluster_types.go
  config/apiresourceschema/singapore.open-cluster-management.io_registeredclusters.yaml
  config/crd/singapore.open-cluster-management.io_registeredclusters.yaml
  controllers/cluster-registration/suite_test.go
  hack/clusterregistrar.yaml
  hack/compute/apibinding.yaml
  hack/compute/apiexport.yaml
  hack/compute/role.yaml
  hack/compute/role_binding.yaml
  hack/hubconfig.yaml
  hack/namespace.yaml
  hack/registeredcluster.yaml
Labels: approved, lgtm, dco-signoff: yes

#12 change go get to go install for cases we really need to install
  Makefile
Labels: approved, lgtm, dco-signoff: yes

#14 change go get to go install for cases we really need to install
  Makefile
Labels: approved, lgtm, dco-signoff: yes
